version: "3.7"

services:
  server:
    container_name: emoi-chat
    image: ignission/emoi-chat:latest
    environment:
      JAVA_OPTIONS: -Dconfig.resource=local.conf
      OPENVIDU_SERVER_URL: https://kms:4443
    ports:
      - 8855:8855
    depends_on:
      - kms

  kms:
    container_name: emoi-kms
    image: openvidu/openvidu-server-kms:2.13.0
    environment:
      openvidu.secret: MY_SECRET
    ports:
      - 4443:4443

  db:
    container_name: emoi-db
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=emoi
      - MYSQL_USER=emoi
      - MYSQL_PASSWORD=emoi
      - MYSQL_ROOT_PASSWORD=emoi
    ports:
      - 33055:3306

volumes:
  db-data:
