version: "3.7"

services:
  api:
    container_name: jam-api
    image: ignission/jam-api:latest
    environment:
      JAVA_OPTIONS: -Dconfig.resource=local.conf
      OPENVIDU_SERVER_URL: https://kms:4443
    ports:
      - 8855:8855
    depends_on:
      - kms

  kms:
    container_name: jam-kms
    image: openvidu/openvidu-server-kms:2.14.0
    environment:
      openvidu.secret: MY_SECRET
    ports:
      - 4443:4443

  db:
    container_name: jam-db
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=jam
      - MYSQL_USER=jam
      - MYSQL_PASSWORD=jam
      - MYSQL_ROOT_PASSWORD=jam
    ports:
      - 33055:3306

  db-test:
    container_name: jam-db-test
    image: mysql:5.7
    volumes:
      - ./docker/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=jam
      - MYSQL_USER=jam
      - MYSQL_PASSWORD=jam
      - MYSQL_ROOT_PASSWORD=jam
    ports:
      - 33056:3306

volumes:
  db-data:

networks:
  default:
    name: jam-network
