version: "3.7"

services:
  server:
    container_name: jam-server
    image: ignission/jam-server:latest
    environment:
      JAVA_OPTIONS: -Dconfig.resource=local.conf
      OPENVIDU_SERVER_URL: https://kms:4443
    ports:
      - 8855:8855
    depends_on:
      - kms

  kms:
    container_name: jam-kms
    image: openvidu/openvidu-server-kms:2.14.0
    environment:
      openvidu.secret: MY_SECRET
    ports:
      - 4443:4443

networks:
  default:
    name: jam-network
