version: "3.7"

services:
  http:
    image: jam-scala
    build: ./docker/scala
    entrypoint: sbt "http/flywayMigrate; ~http/reStart"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
    volumes:
      - ./jam-server:/work
      - cache:/root/.cache

  websocket:
    image: jam-scala
    build: ./docker/scala
    entrypoint: sbt "~websocket/reStart"
    volumes:
      - ./jam-server:/work
      - cache:/root/.cache

  client:
    container_name: jam-client
    image: jam-node
    build: ./docker/node
    ports:
      - 3000:3000
    volumes:
      - ./jam-client:/work
      - node_modules:/work/node_modules

volumes:
  cache:
  node_modules:
