version: "3.7"

services:

  redis:
    container_name: jam-redis
    image: redis:6.2
    ports:
      - 16379:6379

  kms:
    container_name: jam-kms
    image: openvidu/openvidu-server-kms:2.17.0
    environment:
      openvidu.secret: MY_SECRET
    ports:
      - 4443:4443

  db:
    container_name: jam-db
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=jam
      - MYSQL_USER=jam
      - MYSQL_PASSWORD=jam
      - MYSQL_ROOT_PASSWORD=jam
    ports:
      - 33055:3306

  db-test:
    container_name: jam-db-test
    image: mysql:5.7
    volumes:
      - ./docker/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=jam
      - MYSQL_USER=jam
      - MYSQL_PASSWORD=jam
      - MYSQL_ROOT_PASSWORD=jam
    ports:
      - 33056:3306

volumes:
  db-data:

networks:
  default:
    name: jam-network
