name: Build server

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - master

jobs:

  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: cache node_modules
        uses: actions/cache@v1
        id: client_node_modules
        with:
          path: emoi-client/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/emoi-client/yarn.lock')}}
  
      - name: yarn install
        if: steps.client_node_modules.outputs.cache-hit != 'true'
        uses: Borales/actions-yarn@master
        with:
          cmd: --cwd emoi-client install

      - name: yarn build
        uses: Borales/actions-yarn@master
        with:
          cmd: --cwd emoi-client build

      - name: upload artifacts of the client
        uses: actions/upload-artifact@master
        with:
          name: client-artifacts
          path: emoi-server/src/main/resources/static

  build-server:
    runs-on: ubuntu-latest
    needs: build-client
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          version: 1.8
      
      - name: Cache ivy
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-ivy-cache-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-sbt-ivy-cache-

      - name: Cache coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-sbt-coursier-cache-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-sbt-coursier-cache-

      - name: Cache sbt
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-cache-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-sbt-cache-
      
      - name: Check format
        run: |
          cd emoi-server
          sbt scalafmtCheck test:scalafmtCheck scalafmtSbtCheck

      - name: Test
        run: |
          cd emoi-server
          sbt test

