name: Build server

on:
  push:
    branches:
      - 'master'
    paths:
      - 'emoi-server/**'
  pull_request:
    branches:
      - master
    paths:
      - 'emoi-server/**'

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          version: 1.8
      
      - name: Cache ivy
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-ivy-cache-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-sbt-ivy-cache-

      - name: Cache coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-sbt-coursier-cache-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-sbt-coursier-cache-

      - name: Cache sbt
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-cache-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-sbt-cache-
      
      - name: Check format
        run: |
          sbt scalafmtCheck test:scalafmtCheck scalafmtSbtCheck

      - name: Test
        run: |
          cd emoi-server
          sbt test