name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/jam-client/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: cd jam-client && yarn --frozen-lockfile

      - name: Build
        run: cd jam-client && yarn build

      - name: Upload artifacts of the client
        uses: actions/upload-artifact@master
        with:
          name: client-artifacts
          path: jam-server/public

  build-server:
    runs-on: ubuntu-latest
    needs: build-client
    env:
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"

      - uses: actions/download-artifact@v2
        with:
          name: client-artifacts
          path: jam-server/public

      - name: Coursier cache
        uses: coursier/cache-action@v6

      - name: Build and test
        run: |
          sbt -v "checkAll; +test"
        shell: bash