name: docker image

on:
  push:
    branches:
      - "master"

jobs:
  build-websocket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache ivy
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-ivy-cache-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-sbt-ivy-cache-

      - name: Cache coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-sbt-coursier-cache-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-sbt-coursier-cache-

      - name: Cache sbt
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-cache-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-sbt-cache-

      - name: Check format
        run: |
          cd jam-server
          sbt formatCheck

      - name: Check lint
        run: |
          cd jam-server
          sbt fixCheck

      - name: Assembly
        run: |
          cd jam-server
          sbt websocket/assembly
          cd ../
          mkdir -p docker/websocket/dist
          mv jam-server/jam-websocket/target/scala-2.13/jam-websocket.jar docker/websocket/dist

      - name: Upload artifacts of the server
        uses: actions/upload-artifact@master
        with:
          name: websocket-artifacts
          path: docker/websocket/dist

  build-image:
    runs-on: ubuntu-latest
    needs: build-websocket
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: websocket-artifacts
          path: docker/websocket/dist

      - name: Build docker image
        run: |
          docker build -t ignission/jam-websocket:latest docker/websocket

      - name: Push docker image
        run: |
          VERSION=`cat jam-server/build.sbt | grep -E 'version := "(.+?)"' | awk -F' := ' '{print $2}' | sed 's/"//g' | sed 's/,//g'`
          docker login --username shomatan -p ${{ secrets.DOCKER_LOGIN_TOKEN }}
          docker tag ignission/jam-websocket:latest ignission/jam-websocket:$VERSION
          docker push ignission/jam-websocket:latest
          docker push ignission/jam-websocket:$VERSION
